integer(C_int), parameter :: sizeof_C_regex_t = 24_C_int
integer(C_int), parameter :: REG_EXTENDED = 0_C_int
integer(C_int), parameter :: REG_ICASE    = 1_C_int
integer(C_int), parameter :: REG_NEWLINE  = 2_C_int
integer(C_int), parameter :: REG_NOSUB    = 32_C_int
integer(C_int), parameter :: REG_NOTBOL = 4_C_int
integer(C_int), parameter :: REG_NOTEOL = 8_C_int
integer(C_int), parameter :: REG_NOMATCH = 17_C_int
